name: Semgrep SAST

on:
  workflow_call:
  workflow_dispatch:

jobs:
  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/default
            p/security-audit
          generateSarif: "1"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
